version: "3.9"
networks:
  web2:
    driver: bridge
services:
  app: 
    container_name: page-with-comments
    image: zergar5/web2:page-with-comments
    ports:
      - "3000:80"
    networks:
      - web2
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: comments
    ports:
      - "5432:5432"
    networks:
      - web2
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: